# This workflow runs CI checks on all pushes/PRs and deploys to GitHub Pages on main branch
name: CI-CD Integration

permissions:
  id-token: write
  contents: write
  pages: write
  pull-requests: write

# Trigger CI on all pushes and PRs, and CD only on pushes to main
# on:
#   push: # Trigger on any push
#   pull_request: # Trigger on any pull request

on:
  push:
    branches: ["main", "dev", "stagging"] # Trigger on push to main, dev, or stagging branches
  pull_request:
    branches: ["main", "dev", "stagging"] # Trigger on PR to main, dev, or stagging branches
  workflow_dispatch: # only this will allow us to manually trigger the ci-cd workflow
    inputs:
      run-name:
        description: 'Custom run name (optional)'
        required: false
        default: ''
# Note: The workflow name itself cannot be dynamic, but you can set a dynamic run name for workflow_dispatch runs.


jobs:
  # CI Job: Lint, Format, Test, etc.
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Run Name and Commit Timestamp
        run: |
          echo "Workflow Run Name: ${{ github.event.inputs.run-name != '' && github.event.inputs.run-name || format('CI-CD Run {0}', github.run_id) }}"
          echo "Commit Timestamp: ${{ github.event.head_commit.timestamp }}"
      - uses: actions/checkout@v4 # Checkout repository code
        with:
          fetch-depth: 0 # Fetch all history for accurate commit info

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Set up Node.js environment
        with:
          node-version: '22.x' # Use Node.js version 22.x
          cache: 'npm' # Enable npm cache for faster installs
          cache-dependency-path: package-lock.json # Cache based on lock file
          
      - name: Install Dependencies
        run: npm ci # Install dependencies using clean install

      - name: Run Lint
        run: npm run lint # Run linter to check code quality

      - name: Run Formatter
        run: npm run lint:format # Run code formatter

      - name: Run tests and generate coverage report
        run: npm test -- --coverage --coverageReporters=cobertura # Example for a Node.js project

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0 # Replace with the actual action you choose
        with:
          filename: ./coverage/cobertura-coverage.xml # Path to your generated coverage report
          # filename: coverage/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md   

# CD Job: Build and Deploy to Production (only on main branch)
  build-and-deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Echo Run Name and Commit Timestamp
        run: |
          echo "Workflow Run Name: ${{ github.event.inputs.run-name != '' && github.event.inputs.run-name || format('CI-CD Run {0}', github.run_id) }}"
          echo "Commit Timestamp: ${{ github.event.head_commit.timestamp }}"
      - uses: actions/checkout@v4 # Checkout repository code
        with:
          persist-credentials: false # Recommended for GitHub Pages

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Set up Node.js environment
        with:
          node-version: '22.x' # Use Node.js version 22.x
          cache: 'npm' # Enable npm cache for faster installs
          cache-dependency-path: package-lock.json # Cache based on lock file

      - name: Install Dependencies
        run: npm ci # Install dependencies using clean install

      - name: Build
        env:
          VITE_MY_SECRET: ${{ secrets.YOUR_SECRET_NAME }}      
        run: npm run build # Build the project

      # Deploy to github pages
      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

# End of workflow